# Generated by Django 3.2.23 on 2024-03-02 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('mdate', models.CharField(default=datetime.date(2024, 3, 2), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=200)),
                ('alert_date', models.CharField(default=1, max_length=20)),
                ('latitude', models.CharField(default=1, max_length=20)),
                ('longitude', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accno', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='whether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=1, max_length=200)),
                ('weather', models.CharField(default=1, max_length=200)),
                ('date', models.CharField(default=datetime.datetime(2024, 3, 2, 12, 13, 30, 599169), max_length=200)),
                ('temp', models.CharField(default=1, max_length=200)),
                ('description', models.CharField(default=1, max_length=200)),
                ('humidity', models.CharField(default=1, max_length=200)),
                ('pressure', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('Login', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('SUBADMIN', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.subadmin')),
            ],
        ),
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('housename', models.CharField(default=1, max_length=200)),
                ('place', models.CharField(default=1, max_length=200)),
                ('post', models.CharField(default=1, max_length=200)),
                ('pin', models.CharField(default=1, max_length=200)),
                ('phno', models.CharField(default=1, max_length=200)),
                ('joiningdate', models.CharField(max_length=200)),
                ('dismisaldate', models.CharField(max_length=200)),
                ('VOLUNTEER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='subemergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date', models.CharField(default=datetime.datetime(2024, 3, 2, 12, 13, 30, 599169), max_length=200)),
                ('SUBADMIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.subadmin')),
            ],
        ),
        migrations.CreateModel(
            name='SLOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalslot', models.CharField(max_length=200)),
                ('currentslot', models.CharField(max_length=200)),
                ('VOLUNTEER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
                ('quantityt', models.CharField(max_length=200)),
                ('date', models.CharField(default=datetime.date(2024, 3, 2), max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('VOLUNTEER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('feedbackdate', models.CharField(default=datetime.date(2024, 3, 2), max_length=200)),
                ('VOLUNTEER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='complaintesandreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=200)),
                ('reply', models.CharField(default='pending', max_length=200)),
                ('complaintdate', models.CharField(default=datetime.date(2024, 3, 2), max_length=200)),
                ('replydate', models.CharField(default=1, max_length=200)),
                ('VOLUNTEER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='campallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('CAMP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.camp')),
                ('Volunteer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='SUBADMIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.subadmin'),
        ),
    ]
