
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('', views.default),
    path('login_post', views.login_post),
    path('admin_alert_add', views.admin_alert_add),
    path('admin_alert_dlt/<alertid>', views.admin_alert_dlt),
    path('alertadd_post', views.alertadd_post),
    path('alert_view',views.alert_view),
    path('admin_alert_edit/<alertid>',views.admin_alert_edit),
    path('alertedit_post/<alertid>',views.alertedit_post),
    path('admin_camp_view',views.admin_camp_view),
    path('admin_don_view',views.admin_don_view),
    path('admin_msg_add',views.admin_msg_add),
    path('admin_msg_edit/<mid>',views.admin_msg_edit),
    path('admin_msg_dlt/<mid>',views.admin_msg_dlt),
    path('msgedit_post/<mid>',views.msgedit_post),

    path('admin_msg_view',views.admin_msg_view),
    path('sa_admin_msg_view',views.sa_admin_msg_view),
    path('vol_admin_msg_view',views.vol_admin_msg_view),
    path('admin_prc_view',views.admin_prc_view),
    path('admin_prc_edit/<pid>',views.admin_prc_edit),
    path('admin_prc_dlt/<pid>', views.admin_prc_dlt),
    path('admin_prc_addd',views.admin_prc_addd),
    path('admin_subadmin_add',views.admin_subadmin_add),
    path('subadd_post', views.subadd_post),
    path('admin_subadmin_edit/<subid>',views.admin_subadmin_edit),
    path('admin_subadmin_dlt/<subid>',views.admin_subadmin_dlt),
    path('subedit_post/<subid>',views.subedit_post),
    path('admin_subadmin_view',views.admin_subadmin_view),
    path('admin_vol_view',views.admin_vol_view),
    path('admin_whether_add',views.admin_whether_add),
    path('admin_whether_view',views.admin_whether_view),
    path('admin_home',views.admin_home),
    path('prcaadd_post',views.prcaadd_post),
    path('prcedit_post/<pid>', views.prcedit_post),
    path('subedit_post',views.subedit_post),
    path('whetheradd_post',views.whetheradd_post),
    path('whetheredit_post/<whetherid>',views.whetheredit_post),
    path('admin_whether_edit/<whetherid>', views.admin_whether_edit),
    path('admin_whether_dlt/<whetherid>', views.admin_whether_dlt),
    path('subadmin_home',views.subadmin_home),


    path('msgadd_post',views.msgadd_post),
    path('sa_campadd', views.sa_campadd),
    path('campadd_post', views.campadd_post),
    path('subadmin_campview',views.subadmin_campview),
    path('sa_voladd',views.sa_voladd),
    path('voladd_post', views.voladd_post),
    path('subadmin_volview/<campid>',views.subadmin_volview),
    path('sa_msgadd',views.sa_msgadd),
    path('sa_msgadd_post', views.sa_msgadd_post),
    path('subadmin_msgaddview',views.subadmin_msgaddview),
    path('subadmin_cmplrplyview',views.subadmin_cmplrplyview),
    path('subadmin_feedbackview',views.subadmin_feedbackview),
    path('subadmin_chpass',views.subadmin_chpass),
    path('chpass_post', views.chpass_post),
    path('sa_campedit/<campid>', views.sa_campedit),
    path('campedit_post/<campid>', views.campedit_post),
    path('sa_campdlt/<campid>', views.sa_campdlt),
    path('sa_msgdlt/<msgid>', views.sa_msgdlt),
    path('sub_vol_dlt/<campid>', views.sub_vol_dlt),
    path('sa_msgedit/<msgid>', views.sa_msgedit),
    path('sa_msgedit_post/<msgid>', views.sa_msgedit_post),
    path('sa_rply/<cid>', views.sa_rply),
    path('rply_post/<cid>', views.rply_post),

    path('volunteer_home',views.volunteer_home),
    path('slot_add',views.slot_add),
    path('slotadd_post', views.slotadd_post),
    path('vol_slot_view',views.vol_slot_view),
    path('vol_slot_edit/<volid>', views.vol_slot_edit),
    path('vol_slotedit_post/<volid>', views.vol_slotedit_post),
    path('VOL_SLOdlt/<volid>', views.VOL_SLOdlt),
    path('need_add',views.need_add),
    path('needadd_post', views.needadd_post),
    path('sa_alert_view', views.sa_alert_view),

    path('vol_need_view',views.vol_need_view),
    path('vol_alert_view',views.vol_alert_view),
    path('VOL_needdlt/<volid>', views.VOL_needdlt),
    path('userdb_add',views.userdb_add),
    path('userdbadd_post',views.userdbadd_post),
    path('vol_userdb_view',views.vol_userdb_view),
    path('VOL_userdb_dlt/<volid>', views.VOL_userdb_dlt),
    path('feedback_snt',views.feedback_snt),
    path('feedbacksnt_post',views.feedbacksnt_post),
    path('cmplnt_snt',views.cmplnt_snt),
    path('cmplntsnt_post',views.cmplntsnt_post),
    path('vol_rply_view', views.vol_rply_view),
    path('vol_need_edit/<volid>', views.vol_need_edit),
    path('vol_need_post/<volid>', views.vol_need_post),
    path('filled/<id>', views.filled),
    path('vol_chpass',views.vol_chpass),
    path('vol_chpass_post', views.vol_chpass_post),
    path('admin_index',views.admin_index),
    path('sa_admin_index',views.sa_admin_index),
    path('vol_index', views.vol_index),
    path('logout/', views.logout),
    path('subadmin_whether_view', views.subadmin_whether_view),

    path('nearestcamp', views.nearestcamp),
    path('viewneeds', views.viewneeds),
    path('viewprecautions', views.viewprecautions),
    path('connect', views.connect),
    path('viewalerts', views.viewalerts),
    path('payment', views.payment),

    path('sub_userdb_view',views.sub_userdb_view),
    path('sub_volunteer_allocation', views.sub_volunteer_allocation),
    path('subadmin_view_allocation_status', views.subadmin_view_allocation_status),
    path('volunteer_unapproved', views.volunteer_unapproved),
    path('approve_request/<id>', views.approve_request),
    path('reject_request/<id>', views.reject_request),
    path('sub_volunteer_allocation_post', views.sub_volunteer_allocation_post),


]